# Generated by Django 2.1.5 on 2019-02-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblpropertyallocation',
            old_name='pa_agreement_and_date',
            new_name='pa_agreement_end_date',
        ),
    ]
