# Generated by Django 2.1.5 on 2019-03-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrentcollection',
            name='rc_year',
            field=models.IntegerField(max_length=4),
        ),
    ]
