# Generated by Django 2.1.5 on 2019-02-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblagent',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
