# Generated by Django 2.1.5 on 2019-02-06 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20190206_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblagent',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
