# Generated by Django 2.1.5 on 2019-03-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20190318_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrentcollection',
            name='rc_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tblrentcollection',
            name='rc_year',
            field=models.IntegerField(),
        ),
    ]
