# Generated by Django 2.1.5 on 2019-03-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20190219_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblpropertyallocation',
            old_name='pa_acceptance_latter',
            new_name='pa_acceptance_letter',
        ),
    ]
