# Generated by Django 2.1.5 on 2019-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_auto_20190318_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblrentcollection',
            name='rc_year',
        ),
        migrations.AddField(
            model_name='tblrentcollection',
            name='rc_recipt',
            field=models.ImageField(default=None, upload_to='rent/rent_recipt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblrentcollection',
            name='rc_month',
            field=models.DateField(),
        ),
    ]
