# Generated by Django 2.1.5 on 2019-03-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_auto_20190309_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpropertyallocation',
            name='pa_agreement_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tblpropertyallocation',
            name='pa_agreement_end_date',
            field=models.DateField(null=True),
        ),
    ]
