# Generated by Django 2.1.5 on 2019-02-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_auto_20190212_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblmasterpropertyclone',
            name='cln_is_master_clone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblproperty',
            name='pr_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
