# Generated by Django 2.1.5 on 2019-03-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_auto_20190309_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpropertyallocation',
            name='pa_final_rent',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
